config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :items, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    member do
      get 'order'
    end

    resources :orders, only: [:index, :create]
  end

  root to: 'items#index'
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
 
  belongs_to :user
  has_one_attached :image
  belongs_to :category
  belongs_to :condition
  belongs_to :shipping_cost_responsibility
  belongs_to :shipping_from_region
  belongs_to :days_until_shipment
  has_one :order
 
  validates :image, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999, only_integer: true }
  validates :category_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :condition_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :shipping_cost_responsibility_id, numericality: { other_than: 1 , message: "can't be blank"}
  validates :shipping_from_region_id, numericality:{ other_than: 1 , message: "can't be blank"}
  validates :days_until_shipment_id, numericality: { other_than: 1 , message: "can't be blank"}
  

  def sold_out?
    order.present?
  end
end



  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def new
    @item = current_user.items.build
  end

  def create
    @item = current_user.items.build(item_params)

    if @item.save
      redirect_to root_path
    else
      puts @item.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @items = Item.order(created_at: :desc)
  end

  def show
    unless @item.sold_out?
      render :show
      return
    end

    @order = Order.find_by(item_id: @item.id)
    if user_signed_in? && @item.user == current_user && !@order&.purchased?
      @editable = true
    else
      @editable = false
    end
  end

  def edit
    unless current_user == @item.user && !@item.sold_out? && !@item.order&.purchased?
      redirect_to root_path
    end
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @item.user == current_user
      @item.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :image, :category_id, :condition_id, :shipping_cost_responsibility_id, :shipping_from_region_id, :days_until_shipment_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用しています。app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png', size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
        
      <!-- 商品画像 -->
      <div class="img-upload">
        <div class="weight-bold-text">
          商品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <!-- /商品画像 -->

      <!-- 商品名と商品説明 -->
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <!-- /商品名と商品説明 -->

      <%# 商品の詳細 %>
      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, { class: "select-box", id: "item-category" }) %>
          <div class="weight-bold-text">
            商品の状態
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, { class: "select-box", id: "item-condition" }) %>
        </div>
      </div>
      <%# /商品の詳細 %>

      <%# 配送について %>
      <div class="items-detail">
        <div class="weight-bold-text question-text">
          <span>配送について</span>
          <a class="question" href="#">?</a>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            配送料の負担
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_cost_responsibility_id, ShippingCostResponsibility.all, :id, :name, {}, { class: "select-box", id: "shipping_cost_responsibility" }) %>
          <div class="weight-bold-text">
            発送元の地域
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_from_region_id, ShippingFromRegion.all, :id, :name, {}, { class: "select-box", id: "shipping_from_region" }) %>
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:days_until_shipment_id , DaysUntilShipment.all, :id, :name, {}, { class: "select-box", id: "days_until_shipment" }) %>
        </div>
      </div>
      <%# /配送について %>

     <!-- 販売価格 -->
      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>販売価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
            </span>
          </div>
        </div>
      </div>
      <!-- /販売価格 -->

      <%# 注意書き %>
      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
        <p class="sentence">
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          <a href="#">偽ブランドの販売</a>
          は犯罪であり処罰される可能性があります。
        </p>
        <p class="sentence">
          また、出品をもちまして
          <a href="#">加盟店規約</a>
          に同意したことになります。
        </p>
      </div>
      <%# /注意書き %>

      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する", class: "sell-btn" %>
       <%= link_to 'もどる', item_path, class: "back-btn" %>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png', size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima, Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      人生を変えるフリマアプリ
    </h2>
    <p class='service-explain'>
      FURIMAはだれでもかんたんに出品・購入できる
    </p>
    <p class='service-explain'>
      フリマアプリです
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      FURIMAが選ばれる3つの理由
    </h2>
    <ul class='reason-lists'>
      <%# 3つの理由の表示部分... %>
    </ul>
  </div>
  <%# /FURIMAが選ばれる3つの理由部分 %>

  <%# 画面中央の「会員数日本一位」帯部分 %>
  <div class='ad-contents'>
    <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("app-store.svg", class:"apple-btn"), "#" %>
      <%= link_to image_tag("google-play.png", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面中央の「会員数日本一位」帯部分 %>

  <%# FURIMAの特徴 %>
  <div class='feature-contents'>
    <h2 class='title'>
      FURIMAの特徴
    </h2>
    <ul class='feature-lists'>
      <%# 特徴の表示部分... %>
    </ul>
  </div>
  <%# /FURIMAの特徴 %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle">
      新規投稿商品
    </div>
    <ul class='item-lists'>
      <% if @items.blank? %>
        <li class='list'>
          <%= link_to '#' do %>
            <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
            <div class='item-info'>
              <h3 class='item-name'>
                商品を出品してね！
              </h3>
              <div class='item-price'>
                <span>99999999円<br>(税込み)</span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% else %>
        <% @items.each do |item| %>
          <li class='list'>
            <%= link_to item_path(item) do %>
              <div class='item-img-content'>
                <%= image_tag item.image.variant(resize: '300x300'), class: 'item-img' if item.image.attached? %>
                <% if item.sold_out? %>
                  <div class='sold-out'> 
                    <span>Sold Out!!</span>
                  </div> 
                <% end %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= item.name %>
                </h3>
                <div class='item-price'>
                  <span><%= "#{item.price}円" %><br><%= item.shipping_cost_responsibility.name %></span>
                  <div class='star-btn'>
                    <%= image_tag "star.png", class:"star-icon" %>
                    <span class='star-count'>0</span>
                  </div>
                </div>
              </div>
            <% end %> 
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <!-- 出品ボタン -->
  <%= link_to new_item_path, class: 'purchase-btn' do %>
    <span class='purchase-btn-text'>出品する</span>
    <%= image_tag 'icon_camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png', size: '185x50'), "/" %>
  </header>

  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>

    <%= form_with model: @item, url: items_path, local: true do |f| %>

 
      <%= render 'shared/error_messages', model: f.object %>

      <!-- 商品画像 -->
      <div class="img-upload">
        <div class="weight-bold-text">
          商品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <!-- /商品画像 -->

      <!-- 商品名と商品説明 -->
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <!-- /商品名と商品説明 -->

      <!-- 商品の詳細 -->
      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class: "select-box", id: "item-category"}) %>
          <div class="weight-bold-text">
            商品の状態
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:condition_id, Condition.all, :id, :name, {}, {class: "select-box", id: "item-sales-status"}) %>
        </div>
      </div>
      <!-- /商品の詳細 -->

      <!-- 配送について -->
      <div class="items-detail">
        <div class="weight-bold-text question-text">
          <span>配送について</span>
          <a class="question" href="#">?</a>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            配送料の負担
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_cost_responsibility_id, ShippingCostResponsibility.all, :id, :name, {}, {class: "select-box", id: "item-shipping-fee-status"}) %>
          <div class="weight-bold-text">
            発送元の地域
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_from_region_id, ShippingFromRegion.all, :id, :name, {}, {class: "select-box", id: "item-prefecture"}) %>
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:days_until_shipment_id, DaysUntilShipment.all, :id, :name, {}, {class: "select-box", id: "item-scheduled-delivery"}) %>
        </div>
      </div>
      <!-- /配送について -->

      <!-- 販売価格 -->
      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>販売価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>
            </span>
          </div>
        </div>
      </div>
      <!-- /販売価格 -->

      <!-- 注意書き -->
      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
        <p class="sentence">
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          <a href="#">偽ブランドの販売</a>
          は犯罪であり処罰される可能性があります。
        </p>
        <p class="sentence">
          また、出品をもちまして
          <a href="#">加盟店規約</a>
          に同意したことになります。
        </p>
      </div>
      <!-- /注意書き -->

      <!-- 下部ボタン -->
      <div class="sell-btn-contents">
        <%= f.submit "出品する", class: "sell-btn" %>
        <%= link_to 'もどる', user_session_path, class: "back-btn" %>
      </div>
      <!-- /下部ボタン -->
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <% if @item.image.attached? %>
        <%= image_tag @item.image.variant(resize: '700x700'), class: 'item-image' %>
      <% end %>
      <% if @item.sold_out? %> 
        <div class='sold-out'>
          <span>Sold Out!!</span>
        </div> 
      <% end %> 
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.price.to_i.to_s %>
      </span>
      <span class="item-postage">
        <%= @item.shipping_cost_responsibility.name %>
      </span>
    </div>

    <% if user_signed_in? && !@item.sold_out? %>
      <% if @item.user == current_user %>
        <%= link_to "商品の編集", edit_item_path(@item), class: "item-red-btn" %>
        <%= link_to "削除", @item, method: :delete, data: {turbo_method: :delete}, class:"item-destroy" %>
      <% else %>
        <%= link_to "購入画面に進む", item_orders_path(@item), data: { turbo: false },class: "item-red-btn" %>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @item.name %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">商品の状態</th>
          <td class="detail-value"><%= @item.condition.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.shipping_cost_responsibility.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.shipping_from_region.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.days_until_shipment.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>
  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @item.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>

  
  
  
  
  
  
   